INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Which of the following is a compute service in AWS?', 'Amazon S3', 'Amazon EC2', 'Amazon RDS', 'Amazon DynamoDB', 'B'),
('Which AWS service is used to store objects, such as files and images?', 'Amazon EC2', 'Amazon S3', 'Amazon RDS', 'Amazon VPC', 'B'),
('Which AWS service is used for managed MySQL and PostgreSQL databases?', 'Amazon Redshift', 'Amazon Aurora', 'Amazon DynamoDB', 'Amazon RDS', 'D'),
('Which service allows you to run containerized applications in AWS?', 'Amazon EC2', 'AWS Lambda', 'Amazon ECS', 'Amazon RDS', 'C'),
('What is the purpose of AWS CloudFormation?', 'File storage', 'Automate infrastructure provisioning', 'Data analytics', 'DNS management', 'B'),
('Which AWS service is used for monitoring and observability?', 'AWS CloudTrail', 'AWS CloudWatch', 'AWS IAM', 'Amazon VPC', 'B'),
('What is the maximum size of an object you can store in Amazon S3?', '1 TB', '5 TB', '10 TB', '50 TB', 'B'),
('Which service is best for real-time processing of streaming data?', 'Amazon RDS', 'Amazon Kinesis', 'Amazon S3', 'AWS Lambda', 'B'),
('Which AWS service is used for DNS management?', 'Amazon CloudFront', 'Amazon Route 53', 'AWS IAM', 'AWS CloudTrail', 'B'),
('What is the use of AWS IAM?', 'File storage', 'Identity and access management', 'Data encryption', 'Server management', 'B'),
('Which of the following can be used to create a virtual network in AWS?', 'Amazon RDS', 'Amazon VPC', 'AWS IAM', 'AWS Lambda', 'B'),
('Which AWS service allows you to automate software deployment to a fleet of EC2 instances?', 'AWS CodeDeploy', 'Amazon CloudFront', 'Amazon RDS', 'AWS CloudTrail', 'A'),
('Which service is a fully managed NoSQL database in AWS?', 'Amazon RDS', 'Amazon Aurora', 'Amazon DynamoDB', 'Amazon Redshift', 'C'),
('Which AWS service provides a petabyte-scale data warehouse?', 'Amazon RDS', 'Amazon S3', 'Amazon DynamoDB', 'Amazon Redshift', 'D'),
('What type of storage is provided by Amazon EBS?', 'Block storage', 'Object storage', 'File storage', 'Tape storage', 'A'),
('Which service helps you to distribute content globally with low latency?', 'Amazon CloudFront', 'Amazon Route 53', 'Amazon S3', 'Amazon EC2', 'A'),
('Which AWS service allows you to run code without provisioning or managing servers?', 'AWS Lambda', 'Amazon EC2', 'Amazon RDS', 'Amazon DynamoDB', 'A'),
('What is the purpose of Amazon SNS?', 'Sending notifications and messages', 'Data analysis', 'Monitoring EC2 instances', 'Database management', 'A'),
('Which of the following services can be used to store session state data in a scalable manner?', 'Amazon RDS', 'Amazon DynamoDB', 'Amazon S3', 'AWS Lambda', 'B'),
('Which AWS service is used for data warehousing?', 'Amazon RDS', 'Amazon Redshift', 'Amazon S3', 'AWS Glue', 'B');